### PR TITLE
Introduce analysis on speedyseq

### LINKED ISSUE #9: New test option
When time allows it might be useful to add one more option in addition to tse and pseq, namely [speedyseq](https://mikemc.github.io/speedyseq).

The priority now is, however, in adding the other tests on alpha, beta etc. first.

### PR DESCRIPTION
**Pull request by RiboRings**
I introduced the melting and agglomeration experiments for speedyseq. The other commands lack an analogue in speedyseq.

Other changes:
* simplified indexing
* plots include speedyseq

### CODE REVIEW

**Comment by antagomir** [comment]
Is there a reason to make this PR to "RiboRings" branch, instead of "main" branch?

**Comment by antagomir** [comment]
Remarks:

1) Is there a reason to make this PR to "RiboRings" branch, instead of "main" branch? Do the PR against main if possible.

2) Testmethod "agglomerate" gives the following error
-TreeSE
Error: 'rank' must be a value from 'taxonomyRanks()'
-> all other methods tests pass

3) In "Absolute" results, the Asnicar taxa are in lowercase, causing duplicate rows to the panel figure -> Fix.

4) Check that all PDF outputs are ok. For some reason I do not see speedyseq results in beta.pdf, check if this could be fixed.

Otherwise all seems good.

**Comment by RiboRings** [comment]
1. I thought this way it would be easier to find bugs before merging into main.
2. I tried to reproduce it but everything ran smoothly.
3. I tried to reproduce it but everything ran smoothly.
4. speedyseq provides alternatives only for `psMelt` and `tax_glom`.

May I know which data sets and sample sizes gave the error of point 2?

**Comment by antagomir** [comment]
1. Testing can be done in this branch and when the automated checks pass and every reviewer is happy with the PR, it can be merged directly to main. Sometimes projects with multiple developers use more complex hierarchies but then this should be arranged into development layers.

2-3. These are related to the fact that taxonomyRanks(containers[[1]]) is with lowercase and 2-3 with uppercase. All should be comparable (i.e. uppercase). Fix this when reading in the data set.

4. Ahaa good!

**Pull request merged**
